// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }

    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError('FirebaseOptions are not configured for iOS.');
      case TargetPlatform.macOS:
        throw UnsupportedError('FirebaseOptions are not configured for macOS.');
      case TargetPlatform.windows:
        throw UnsupportedError(
          'FirebaseOptions are not configured for Windows.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError('FirebaseOptions are not configured for Linux.');
      default:
        throw UnsupportedError(
          'FirebaseOptions are not supported for this platform.',
        );
    }
  }

  /// 🔵 WEB Firebase config (converted from JS)
  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAjEC-OHqURNBnWljJ7FCIBUTePnSN-9QM',
    authDomain: 'smartstay-beb80.firebaseapp.com',
    projectId: 'smartstay-beb80',
    storageBucket: 'smartstay-beb80.firebasestorage.app',
    messagingSenderId: '335173652406',
    appId: '1:335173652406:web:404f51d1e1d5d1f544bb17',
    measurementId: 'G-SS0NGGJ6KJ',
  );

  /// 🤖 ANDROID Firebase config
  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCKPLvr2jNHI-l3o-lj-6DmqPeWV3GmO5w',
    appId: '1:335173652406:android:b884118ee5fb25f944bb17',
    messagingSenderId: '335173652406',
    projectId: 'smartstay-beb80',
    storageBucket: 'smartstay-beb80.firebasestorage.app',
  );
}
